app/recetario/models.py
#########################################################
# MODELOS DE RECETAS
# Aquí se definen todas las tablas que sirven 
# para guardar las recetas: Recetas, Ingredientes y
# su relación
#########################################################

# SQLAlchemy
from sqlalchemy import Column, ForeignKey
from sqlalchemy import Column, Integer, String, Text
from sqlalchemy import DateTime, Float
from sqlalchemy.orm import relationship, backref

# Librerías Python
from datetime import datetime

from sqlalchemy.sql.expression import false, true

# Base de datos
from app import db

# Tablas del referencial
# from app.referencial.models import Categoria, Medida


# Tabla de ingredientes
class Ingrediente(db.Model):

  __tablename__='Ingrediente'
  id = Column(Integer, primary_key=True)
  nombre = Column(String(50), nullable=False)
  descripcion = Column(String(100), nullable=True)
  precio = Column(Float, default=0, nullable=True) 
  medida_id = Column(Integer, ForeignKey('Medida.id', ondelete="CASCADE"), nullable=False)
  medida=relationship("Medida")
  created = Column(DateTime)
  updated = Column(DateTime)

  # Relación
  recetas = relationship("IngredienteReceta") #, backref="ingrediente")

  # Devuelve el nombre
  def __str__(self):
      return self.nombre

  # Hace las diversas validaciones del ingrediente
  def validar(self):
      valido = False
      if self.nombre and self.medida_id:
          valido = True
      return valido

  # Guarda un ingrediente, ya sea nuevo o existente (id)
  def guardar(self):
    if not self.id:
      self.created=datetime.now()
      self.updated=datetime.now()
      db.session.add(self)
    else:
      ingrediente = {'nombre': self.nombre, 
                    'descripcion': self.descripcion,
                    'precio': self.precio,
                    'medida_id': self.medida_id,
                    'updated': datetime.now()
                    }
      self.query.filter_by(id=self.id).update(ingrediente)
    db.session.commit()

  # Elimina un ingrediente dado (id)
  def borrar(self, id):
    borrado = self.query.filter_by(id=id).delete()
    db.session.commit()

    return borrado

  # Devuelve un ingrediente dado (id)
  def buscar(self, id):
    return self.query.get(id)

  # Devuelve la lista de todos los ingredientes
  @staticmethod
  def listar():
    return Ingrediente.query.order_by(Ingrediente.nombre).all()


# Tabla de Recetas
class Receta(db.Model):

  __tablename__='Receta'
  id = Column(Integer, primary_key=True)
  titulo = Column(String(50), nullable=False)
  descripcion = Column(Text, nullable=True)
  categoria_id = Column(Integer, ForeignKey('Categoria.id', ondelete="CASCADE"), nullable=False)
  categoria=relationship("Categoria", backref="Receta")
  costo = Column(Float, default=0.0, nullable=False) 
  ganancia = Column(Float, default=0.0, nullable=False) 
  created = Column(DateTime)
  updated = Column(DateTime)

  # Relación
  ingredientes = relationship("IngredienteReceta") #, backref="receta")

  # Devuelve el nombre
  def __str__(self):
    return self.titulo

  # Hace las diversas validaciones de la receta
  def validar(self):
    valido = False
    if self.titulo and self.categoria_id:
      valido = True
    return valido

  # Guarda una receta, ya sea nueva o existente (id)
  def guardar(self):
    if not self.id:
      self.created=datetime.now()
      self.updated=datetime.now()
      db.session.add(self)
    else:
      receta =  {'titulo': self.titulo, 
                'descripcion': self.descripcion,
                'costo': self.costo,
                'ganancia': self.ganancia,
                'categoria_id': self.categoria_id,
                'updated': datetime.now()
                }
      self.query.filter_by(id=self.id).update(receta)
    db.session.commit()

  # Elimina una receta dada (id)
  def borrar(self, id):
    borrado = self.query.filter_by(id=id).delete()
    db.session.commit()

    return borrado

  # Devuelve una receta dada (id)
  def buscar(self, id):
    return self.query.get(id)

  # Devuelve la lista de todas las recetas
  @staticmethod
  def listar():
    return Receta.query.order_by(Receta.titulo).all()

  # Devuelve la lista de todas las recetas de una categoria
  @staticmethod
  def recetas_categoria(cat_id):
    return Receta.query.filter_by(categoria_id=cat_id).order_by(Receta.titulo).all()


# Tabla de IngredienteReceta
# Asocia recetas con ingredientes
# Relación many to many bidireccional, o sea, permite obtener la lista de
# ingredientes de una receta pero también la lista de recetas que contienen
# un ingediente
class IngredienteReceta(db.Model):

  __tablename__='IngredienteReceta'
  receta_id = Column(Integer, ForeignKey('Receta.id', ondelete="CASCADE"), primary_key=True)
  ingrediente_id = Column(Integer, ForeignKey('Ingrediente.id', ondelete="CASCADE"), primary_key=True) 
  cantidad = Column(Float, default=1, nullable=False) 
  medida_id = Column(Integer, ForeignKey('Medida.id', ondelete="CASCADE"), nullable=False)
  medida=relationship("Medida")
  created = Column(DateTime)
  updated = Column(DateTime)
  
  # Relaciones
  receta = relationship("Receta") #,  cascade="all,delete", backref="ingredientes")
  ingrediente = relationship("Ingrediente") #,  cascade="all,delete", backref="recetas")

  # Hace las diversas validaciones para los ingredientes de una receta
  def validar(self):
    valido = False
    if self.ingrediente_id and self.cantidad and self.medida_id:
      valido = True
    return valido

  # Guarda ingredientes de una receta
  def guardar(self):

    existe = self.query.filter_by(receta_id=self.receta_id, ingrediente_id=self.ingrediente_id).first()

    if not existe:
      self.created=datetime.now()
      self.updated=datetime.now()
      db.session.add(self)
    else:
      ing_receta =  {'receta_id': self.receta_id, 
                'ingrediente_id': self.ingrediente_id,
                'cantidad': self.cantidad,
                'medida_id': self.medida_id,
                'updated': datetime.now()
                }
      self.query.filter_by(receta_id=self.receta_id, ingrediente_id=self.ingrediente_id).update(ing_receta)
    db.session.commit()

  # Elimina un ingrediente de una receta
  def borrar(self, id_rec, id_ing):

    ing_rec = self.query.filter_by(receta_id=id_rec, ingrediente_id=id_ing).first()
    borrado = db.session.delete(ing_rec)
    db.session.commit()

    return borrado

  # Devuelve un ingrediente de una receta dados
  def buscar(self, id_rec, id_ing):
    return self.query.filter_by(receta_id=id_rec, ingrediente_id=id_ing).first()

app/recetario/__init__.py
#########################################################
# INICIALIZACIÓN DEL PAQUETE RECETAS
# Definición del Blueprint
#########################################################

from flask import Blueprint

# Recetas: Nombre del Blueprint
# __name__: Importa el nombre del módulo
# Nombres de los directorios de los templates y los archivos static

recetario_bp = Blueprint('recetario', __name__, template_folder='templates', static_folder='static')

# Importa todas las vistas de módulo para que la app sea conciente de de que existen
from . import routes

app/recetario/routes.py
#########################################################
# VISTAS DEL BLUEPRINT RECETARIO
#########################################################

from flask import redirect, url_for, render_template, flash
from flask import request

# Blueprint
from . import recetario_bp

# Otros módulos
from .models import Ingrediente, Receta
from app.referencial.models import Medida, Categoria
from .gestion_recetas import *


#########################################################
# VISTAS PARA LOS INGREDIENTES
#########################################################

# Lista de todos los ingredientes
@recetario_bp.route('/recetario/lista_ingredientes')
def listar_ingredientes():
    ingredientes = Ingrediente.listar()
    return render_template('/recetario/ingrediente_list.html', ingredientes = ingredientes)

# Consulta un ingrediente dado
# El parámetro acción permite "adaptar" el template
@recetario_bp.route('/recetario/consultar_ingrediente/<id>')
def consultar_ingrediente(id):
    accion = "Consultar"
    ingrediente = Ingrediente()
    un_ingrediente = ingrediente.buscar(id)

    medidas = Medida.listar()

    return render_template('/recetario/ingrediente_detail.html', ingrediente=un_ingrediente, medidas=medidas, accion=accion)

# Crea un ingrediente
# El parámetro acción permite "adaptar" el template
@recetario_bp.route('/recetario/crear_ingrediente', methods=["GET", "POST"])
def crear_ingrediente():
    accion = "Crear"
    ingrediente = Ingrediente()

    medidas = Medida.listar()

    if request.method == 'POST':
        ingrediente.nombre = request.form['nombre']
        ingrediente.descripcion = request.form['descripcion']
        ingrediente.precio = request.form['precio']
        ingrediente.medida_id = request.form['medida_id']
        
        if ingrediente.validar():                     
            ingrediente.guardar()
            mensaje="Ingrediente " + ingrediente.nombre + " creado satisfactoriamente" 
            flash(mensaje)
            return redirect(url_for('recetario.listar_ingredientes'))
              
    return render_template('/recetario/ingrediente_detail.html', ingrediente=ingrediente, medidas=medidas, accion=accion)

# Edita un ingrediente
# El parámetro acción permite "adaptar" el template
@recetario_bp.route('/recetario/editar_ingrediente/<int:id>',  methods=["GET", "POST"])
def editar_ingrediente(id):
    accion = "Editar"
    ingrediente = Ingrediente()
    un_ingrediente = ingrediente.buscar(id)

    medidas = Medida.listar()

    if request.method == 'POST':
        ingrediente.id = id
        ingrediente.nombre = request.form['nombre']
        ingrediente.descripcion = request.form['descripcion']
        ingrediente.precio = request.form['precio']
        ingrediente.medida_id = request.form['medida_id']

        if ingrediente.validar():  
            ingrediente.guardar()
            mensaje="Ingrediente " + ingrediente.nombre + " modificado satisfactoriamente" 
            flash(mensaje)
            return redirect(url_for('recetario.listar_ingredientes'))

    return render_template('/recetario/ingrediente_detail.html', ingrediente=un_ingrediente, medidas=medidas, accion=accion)


# Elimina un ingrediente
@recetario_bp.route('/recetario/eliminar_ingrediente/<int:id>')
def eliminar_ingrediente(id):
    ingrediente = Ingrediente()
    if ingrediente.borrar(id):
        flash('Ingrediente eliminado satisfactoriamente')
    
    return redirect(url_for('recetario.listar_ingredientes'))



#########################################################
# VISTAS PARA LAS RECETAS
# Usamos el módulo gestion_recetas.py donde tratamos
# las recetas junto con sus ingredientes así como
# el cálculo de costos y precios
#########################################################

# Contexto o parámetros que se envían a las páginas relacionadas con las recetas
def contexto_receta(id):
  receta = Receta()
  una_receta = receta.buscar(id)
  ings = None
  precio = 0

  if una_receta:
    ings = una_receta.ingredientes
    una_receta.costo = calculo_costo_receta(id)
    precio = calculo_precio_receta(una_receta.costo, una_receta.ganancia)

  contexto = {
    'receta': una_receta,
    'precio': precio,
    'ingredientes_receta': ings,
    'lista_ingredientes': Ingrediente.listar(),
    'medidas': Medida.listar(),
    'categorias': Categoria.listar()
  }
  return contexto

# Lista de recetas
# Se pueden filtrar según parámetros indicados por el usuario
@recetario_bp.route('/recetario/lista_recetas', methods=["GET", "POST"])
@recetario_bp.route('/recetario/lista_recetas/<int:id_cat>')
@recetario_bp.route('/recetario/lista_recetas/<int:id_ing>')
@recetario_bp.route('/recetario/lista_recetas/<int:id_cat>/<int:id_ing>')
def listar_recetas(id_cat=None, id_ing=None):
  categorias = Categoria.listar()
  ingredientes = Ingrediente.listar()

  if request.method == 'POST':
    id_cat = (int(request.form['categoria_id']) if request.form['categoria_id'] != "None" else None)
    id_ing = (int(request.form['ingrediente_id']) if request.form['ingrediente_id'] != "None" else None)
    recetas = lista_dinamica_recetas(id_cat, id_ing)
    return render_template('/recetario/receta_list.html', recetas=recetas, categorias=categorias, ingredientes=ingredientes, id_cat=id_cat, id_ing=id_ing)
  else:
    recetas = lista_dinamica_recetas()

  return render_template('/recetario/receta_list.html', recetas=recetas, categorias=categorias, ingredientes=ingredientes)


# Consulta una receta dada
# El parámetro acción permite "adaptar" el template
@recetario_bp.route('/recetario/consultar_receta/<int:id>')
def consultar_receta(id):
  accion = "Consultar"

  return render_template('/recetario/receta_detail.html', accion=accion, **contexto_receta(id))


# Tratar (crear o modificar) una receta 
# El parámetro acción permite "adaptar" el template
@recetario_bp.route('/recetario/tratar_receta', methods=["GET", "POST"])
@recetario_bp.route('/recetario/tratar_receta/<int:id>',  methods=["GET", "POST"])
def tratar_receta(id=None):
    accion = ("Editar" if id else "Crear")
    receta = Receta()

    if request.method == 'POST':
      receta.id = id
      receta.titulo = request.form['titulo']
      receta.descripcion = request.form['descripcion']
      receta.costo = request.form['costo']
      receta.ganancia = request.form['ganancia']
      receta.categoria_id = request.form['categoria_id']

      if receta.validar():                     
          receta.guardar()
          mensaje="Receta " + receta.titulo + " procesada satisfactoriamente" 
          flash(mensaje)
          return redirect(url_for('recetario.tratar_receta', id=receta.id))
              
    return render_template('/recetario/receta_detail.html', accion=accion, **contexto_receta(id))

# Elimina una receta
@recetario_bp.route('/recetario/eliminar_receta/<int:id>')
def eliminar_receta(id):
    receta = Receta()
    if receta.borrar(id):
        flash('Receta eliminada satisfactoriamente')
    
    return redirect(url_for('recetario.listar_recetas'))


#########################################################
# VISTAS PARA LOS INGREDIENTES DE UNA RECETA
#########################################################

# Contexto o parámetros que se envían a las páginas relacionadas con ingredientes de una receta
def contexto_ingrediente_receta(id_rec, id_ing):
  ing = IngredienteReceta()
  ing_rec = None
  if id_ing: 
    ing_rec = ing.buscar(id_rec, id_ing)

  contexto = {
    'id_rec': id_rec,
    'ing_rec': ing_rec,
    'lista_ingredientes': Ingrediente.listar(),
    'medidas': Medida.listar(),
  }
  return contexto

# Crea un ingrediente para una receta
@recetario_bp.route('/recetario/tratar_ingrediente_receta/<int:id_rec>', methods=["GET", "POST"])
@recetario_bp.route('/recetario/tratar_ingrediente_receta/<int:id_rec>/<int:id_ing>', methods=["GET", "POST"])
def tratar_ingrediente_receta(id_rec, id_ing=None):
  accion = ("Editar" if id_ing else "Crear")
  ing_rec = IngredienteReceta()

  if request.method == 'POST':
    ing_rec.receta_id = id_rec
    ing_rec.ingrediente_id = request.form['ingrediente_id']
    ing_rec.cantidad = request.form['cantidad']
    ing_rec.medida_id = request.form['medida_id']
    
    if ing_rec.validar():                     
        ing_rec.guardar()
        return redirect(url_for('recetario.tratar_receta', id=id_rec))

  return render_template('/recetario/ing_rec_detail.html', accion=accion, **contexto_ingrediente_receta(id_rec, id_ing))


@recetario_bp.route('/recetario/eliminar_ingrediente_receta/<int:id_rec>/<int:id_ing>')
def eliminar_ingrediente_receta(id_rec, id_ing):
  ing_rec = IngredienteReceta()

  if ing_rec.borrar(id_rec, id_ing):
    flash('Ingrediente eliminado satisfactoriamente')
  
  return redirect(url_for('recetario.tratar_receta', id=id_rec))


app/recetario/templates/recetario/ing_rec_detail.html
{% extends "base.html" %}

{% block title %}
  {{ accion }} Ingrediente de la Receta {{ super() }}
{% endblock  %}

{% block page_title %}

  <h2 class="text-primary">{{ accion }} Ingrediente de la Receta</h2>

{% endblock %}

{% block content %} 

{% if accion == "Crear" %}
  <form action="{{ url_for('recetario.tratar_ingrediente_receta', id_rec=id_rec) }}" method="POST" novalidate> 
    <fieldset enabled>
{% elif accion == "Editar" %}
  <form action="{{ url_for('recetario.tratar_ingrediente_receta', id_rec=id_rec, id_ing=ing_rec.ingrediente_id) }}" method="POST" novalidate> 
    <fieldset enabled>
{% endif %}

    <div class="d-flex flex-row justify-content-between border m-3 p-2">
      <div class="col-sm-4">
        <label for="ingrediente_id" class="col-form-label">Ingredientes</label>
        <select class="form-select" id="ingrediente_id" name="ingrediente_id">
          {% for ingrediente in lista_ingredientes  %}
            <option value="{{ ingrediente.id }}" {% if ingrediente.id==ing_rec.ingrediente_id  %}selected{% endif %}>
              {{ ingrediente.nombre }}</option>
          {% endfor %}
        </select>
      </div>
      <div class="col-sm-2">
        <label for="cantidad" class="col-form-label">Cantidad</label>
        <div>
            <input type="numeric" step="0.01" class="form-control text-right" id="cantidad" name="cantidad"
            value={% if accion != "Crear" %} "{{ ing_rec.cantidad }}" {% else %} "0" {% endif %}>
        </div>
      </div>
      <div class="col-sm-4">
        <label for="medida_id" class="col-form-label">Medida</label>
        <select class="form-select" id="medida_id" name="medida_id" required>
          {% for medida in medidas  %}
          <option value="{{ medida.id }}" {% if medida.id==ing_rec.medida_id  %}selected{% endif %}>
            {{ medida.nombre }}</option>
          {% endfor %}
        </select>
      </div>      
    </div>
    <footer>
      <div class="d-flex flex-row justify-content-between"> 
        <div class="p-2">
          <a class="btn btn-primary" href="{{ url_for('recetario.tratar_receta', id=id_rec) }}" >Volver Receta</a>
        </div> 
        <div class="p-2 align-self-end">
          <button type="Submit" class="btn btn-primary">Validar</button>
        </div>      
      </div>
    </footer>
  </form>       


  {% endblock %}

app/recetario/templates/recetario/ingrediente_detail.html
{% extends "base.html" %}

{% block title %}
  {{ accion }} Ingrediente {{ super() }}
{% endblock  %}

{% block page_title %}

  <h1 class="text-primary">{{ accion }} Ingrediente</h1>

{% endblock %}

{% block content %}

    {% if accion == "Consultar" %}
        <form method="GET"> 
        <fieldset disabled>
    {% elif accion == "Crear" %}
        <form action="{{ url_for('recetario.crear_ingrediente') }}" method="POST" novalidate> 
        <fieldset enabled>
    {% else %}
        <form action="{{ url_for('recetario.editar_ingrediente', id=ingrediente.id) }}" method="POST" novalidate> 
        <fieldset enabled>
    {% endif %}
        <div class="border m-3 p-2">
            <div class="row">
                <div class="col-sm-5">   
                    <label for="nombre" class="col-form-label">Nombre</label>
                    <div>
                        <input type="text" class="form-control" id="nombre" name="nombre" required maxlength=50 
                        value={% if accion == "Crear" %} "" {% else %} "{{ ingrediente.nombre }}" {% endif %} >
                    </div>
                </div>
                <div class="col-sm-7">   
                    <label for="descripcion" class="col-form-label">Descripción</label>
                    <div>
                        <input type="text" class="form-control" id="descripcion" name="descripcion" maxlength=100
                        value={% if accion == "Crear" %} "" {% else %} "{{ ingrediente.descripcion }}" {% endif %} >
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <label for="precio" class="col-form-label">Precio</label>
                    <div class="input-group">
                        <input class="form-control" type="number" name="precio" id="precio" step="0.01" required
                        value={% if accion == "Crear" %} "0" {% else %} "{{ ingrediente.precio }}" {% endif %} >
                        <span class="input-group-text">$</span>
                    </div>
                </div>
                <div class="col-sm-6">
                    <label for="medida_id" class="col-form-label">Medida</label>
                    <select class="form-select" id="medida_id" name="medida_id" required>
                        {% for medida in medidas  %}
                            <option value="{{ medida.id }}" {% if medida.id==ingrediente.medida_id  %}selected{% endif %}>
                            {{ medida.nombre }}</option>
                        {% endfor %}
                    </select>
                </div>                
            </div>
        </div>
        </fieldset>

        <footer>
            <div class="d-flex flex-row justify-content-between">
              <div class="p-2">
                <a class="btn btn-primary" href="{{ url_for('recetario.listar_ingredientes') }}" >Volver a la lista</a>
              </div>    
              {% if accion != "Consultar"  %}
                <div class="p-2">
                  <button type="Submit" class="btn btn-primary">Validar</button>
                </div>
              {% endif %}        
            </div>
          </footer>

    </form>
       
{% endblock %}

    
      
   

app/recetario/templates/recetario/ingrediente_list.html
{% extends "base_list.html" %}

{% block title %}
  Lista de Ingredientes {{ super() }}
{% endblock  %}

{% block page_title %}

  <h1 class="text-primary">Lista de Ingredientes</h1>

{% endblock %}

    {% block table_head %}
      <tr>
          <th>Nombre<i class="fa fa-sort" aria-hidden="true"></i></th>
          <th>Descripción</th>
          <th>Acciones</th>
      </tr>
    {% endblock table_head %}

    {% block table_body %}

       {% for ingrediente in ingredientes %}
          <tr>
             <td>
                <a href="{{ url_for('recetario.consultar_ingrediente', id=ingrediente.id) }}">
                {{ ingrediente.nombre }}</a>
             </td>
             <td>
               <p>{{ ingrediente.descripcion }}</p>
             </td>
             <td>
               <a href="{{ url_for('recetario.consultar_ingrediente', id=ingrediente.id) }}" class="view" title="View" data-toggle="tooltip"><i class="material-icons">&#xE417;</i></a>
               <a href="{{ url_for('recetario.editar_ingrediente', id=ingrediente.id) }}" class="edit" title="Edit" data-toggle="tooltip"><i class="material-icons">&#xE254;</i></a>
               <a href="{{ url_for('recetario.eliminar_ingrediente', id=ingrediente.id) }}" class="delete" title="Delete" data-toggle="tooltip"><i class="material-icons">&#xE872;</i></a>
             </td>
           </tr>
      {% endfor %}   
    {% endblock table_body %}

    {% block others %}
      <div class="col-sm-4">
        <a class="btn btn-primary" href="{{ url_for('recetario.crear_ingrediente') }}" >Nuevo</a>
      </div>
    {% endblock  %}

   


app/recetario/templates/recetario/receta_list.html
{% extends "base_list.html" %}

{% block title %}
  Lista de Recetas {{ super() }}
{% endblock  %}

{% block page_title %}

  <h1 class="text-primary">Lista de Recetas</h1>

{% endblock %}

{% block select %}

  <form method="post" action="{{ url_for('recetario.listar_recetas') }}">
    <div class="d-flex flex-row justify-content-between border m-3 p-2">
      <h6 class="col-sm-2 p-2">Filtrar recetas</h6>
      <div class="col-sm-4 mx-2">
        <select class="form-select" aria-label="Default select example" id="categoria_id" name="categoria_id">
          <option value="None" selected>-- Todas Categorías --</option>
          {% for categoria in categorias  %} 
            <option value="{{ categoria.id }}" {% if  categoria.id==id_cat  %}selected{% endif %}>
            {{ categoria.nombre }}</option>
          {% endfor %}
        </select>
      </div>
      <div class="col-sm-4 mx-2">
        <select class="form-select" id="ingrediente_id" name="ingrediente_id">
          <option value="None" selected>-- Todos Ingredientes --</option>
          {% for ingrediente in ingredientes  %}
              <option value="{{ ingrediente.id }}" {% if ingrediente.id==id_ing  %}selected{% endif %}>
              {{ ingrediente.nombre }}</option>
          {% endfor %}
        </select>
      </div>
      <div class="col-sm-2 mx-2">
        <button type="submit" class="btn btn-primary">Buscar</button>
      </div>      
    </div>   
  </form>

{% endblock select %}

{% block table_head %}
  <tr>
    <th>Título</th>
    <th>Acciones</th>
  </tr>
{% endblock table_head %}

{% block table_body %}

  {% for receta in recetas %}
    <tr>
      <td>
        <a href="{{ url_for('recetario.consultar_receta', id=receta.id) }}">
        {{ receta.titulo }}</a>
      </td>
      <td>
        <a href="{{ url_for('recetario.consultar_receta', id=receta.id) }}" class="view" title="View" data-toggle="tooltip"><i class="material-icons">&#xE417;</i></a>
        <a href="{{ url_for('recetario.tratar_receta', id=receta.id) }}" class="edit" title="Edit" data-toggle="tooltip"><i class="material-icons">&#xE254;</i></a>
        <a href="{{ url_for('recetario.eliminar_receta', id=receta.id) }}" class="delete" title="Delete" data-toggle="tooltip"><i class="material-icons">&#xE872;</i></a>
      </td>
    </tr>
  {% endfor %}   
{% endblock table_body %}

{% block others %}
  <div class="col-sm-4">
    <a class="btn btn-primary" href="{{ url_for('recetario.tratar_receta') }}" >Nuevo</a>
  </div>
{% endblock  %}

  


app/recetario/templates/recetario/receta_tab.html
<!-- Tabs navs -->
<ul class="nav nav-tabs" id="tab-detalle-receta" role="tablist">
  <li class="nav-item" role="presentation"> 
    <a class="nav-link active" data-bs-toggle="tab" id="tab-detalle-receta-1" href="#tab-ingredientes" aria-controls="tab-detalle-receta-1" aria-selected="true">Ingredientes</a>
  </li>
  <li class="nav-item" role="presentation"> 
    <a class="nav-link" data-bs-toggle="tab"  id="tab-detalle-receta-2" href="#tab-preparacion" aria-controls="tab-detalle-receta-2" aria-selected="false">Preparación</a>
  </li>
</ul>
<!-- Tabs navs -->
  
<!-- Tabs content -->
<div class="tab-content mt-2" id="tab-detalle-receta-content">
  <div class="tab-pane fade show active" id="tab-ingredientes" role="tabpanel" aria-labelledby="tab-detalle-receta-1-tab">

    <div class="table-responsive">
      <div class="table-wrapper">
        <table class="table table-striped table-hover table-bordered">
          <thead>
            <th>Ingrediente</th>
            <th>Cantidad</th>
            <th>Unidad</th>
            {% if accion != "Consultar"  %}
              <th>Acciones</th>
            {% endif %}
          </thead>
          <tbody>
            {% if ingredientes_receta  %}
              {% for ing_rec in ingredientes_receta %}
                <tr>
                  <td>
                    {{ ing_rec.ingrediente.nombre }}
                  </td>
                  <td>
                    {{ ing_rec.cantidad }}
                  </td>
                  <td>
                    {{ ing_rec.medida.nombre}}
                  </td>
                  {% if accion != "Consultar"  %}
                    <td>
                      <a href="{{ url_for('recetario.tratar_ingrediente_receta', id_rec=ing_rec.receta_id, id_ing=ing_rec.ingrediente_id) }}" class="edit" title="Editar" data-toggle="tooltip"><i class="material-icons">&#xE254;</i></a>
                      <a href="{{ url_for('recetario.eliminar_ingrediente_receta', id_rec=ing_rec.receta_id, id_ing=ing_rec.ingrediente_id) }}" class="delete" title="Eliminar" data-toggle="tooltip"><i class="material-icons">&#xE872;</i></a>
                    </td>
                  {% endif %}
                </tr>
              {% endfor %}  
            {% endif %}
          </tbody>
        </table>
      </div>
    </div> 

  </div>

  <div class="tab-pane fade" id="tab-preparacion" role="tabpanel" aria-labelledby="tab-detalle-receta-2-tab">
    <div class="form-outline border m-3 p-2">
      <label for="descripcion" class="form-label">Preparación</label>
      <textarea class="form-control" rows="10"  id="descripcion" name="descripcion" {% if accion == "Consultar" %} disabled {% endif %}>  
        {{ receta.descripcion }}                                       
      </textarea>
    </div>
  </div>
</div>
<!-- Tabs content -->