app/referencial/models.py
#########################################################
# MODELOS DEL REFERENCIAL
# Aquí se definen todas las tablas que sirven 
# de referencial
#########################################################

# SQLAlchemy
from sqlalchemy import Column
from sqlalchemy import Column, Integer, String
from sqlalchemy import Float
from sqlalchemy.orm import backref
from sqlalchemy.sql.expression import true

# Base de datos
from app import db

# Tabla de Categorias de recetas
class Categoria(db.Model):

    __tablename__='Categoria'
    id = Column(Integer, primary_key=True)
    nombre = Column(String(50), nullable=False)
    descripcion = Column(String(100))

    # Devuelve el nombre
    def __str__(self):
        return self.nombre

    # Hace las diversas validaciones de la categoria
    def validar(self):
        valido = False
        if self.nombre and len(self.nombre) <= 50 and len(self.descripcion) <= 100:
            valido = true
        return valido

    # Guarda una categoria, ya sea nueva o existente (id)
    def guardar(self):
        if not self.id:
            db.session.add(self)
        else:
            categoria = {'nombre': self.nombre, 'descripcion': self.descripcion}
            self.query.filter_by(id=self.id).update(categoria)
        db.session.commit()

    # Elimina una categoria dada (id)
    def borrar(self, id):
        borrado = self.query.filter_by(id=id).delete()
        db.session.commit()

        return borrado

    # Devuelve una categoria dada (id)
    def buscar(self, id):
        return self.query.get(id)

    # Devuelve la lista de todas las categorias
    @staticmethod
    def listar():
        return Categoria.query.order_by(Categoria.nombre).all()

# Tabla de Unidades de Medida
# Utilizada en los ingredientes para especificar el precio según su unidad de medida
# Y en la lista de ingredientes de una receta
class Medida(db.Model):

    __tablename__='Medida'
    id = Column(Integer, primary_key=True)
    nombre = Column(String(50), nullable=False)
    proporcion = Column(Float, default=1, nullable=False) 

    # Devuelve el nombre
    def __str__(self):
        return self.nombre

    # Hace las diversas validaciones de la unidad de medida
    def validar(self):
        valido = False
        if self.nombre and len(self.nombre) <= 50 and self.proporcion:
            valido = True
        return valido

    # Guarda una medida, ya sea nueva o existente (id)
    def guardar(self):
        if not self.id:
            db.session.add(self)
        else:
            medida = {'nombre': self.nombre, 'proporcion': self.proporcion}
            self.query.filter_by(id=self.id).update(medida)
        db.session.commit()

    # Elimina una categoria dada (id)
    def borrar(self, id):
        borrado = self.query.filter_by(id=id).delete()
        db.session.commit()

        return borrado

    # Devuelve una categoria dada (id)
    def buscar(self, id):
        return self.query.get(id)

    # Devuelve la lista de todas las categorias
    @staticmethod
    def listar():
        return Medida.query.order_by(Medida.nombre).all()



app/referencial/__init__.py
#########################################################
# INICIALIZACIÓN DEL PAQUETE REFERENCIAL
# Definición del Blueprint
#########################################################

from flask import Blueprint

# Recetas: Nombre del Blueprint
# __name__: Importa el nombre del módulo
# Nombres de los directorios de los templates y los archivos static

referencial_bp = Blueprint('referencial', __name__, template_folder='templates', static_folder='static')

# Importa todas las vistas de módulo para que la app sea conciente de de que existen
from . import routes

app/referencial/routes.py
#########################################################
# VISTAS DEL BLUEPRINT REFERENCIAL
#########################################################

from flask import Flask, redirect, url_for, render_template, flash
from flask import request

# Blueprint
from . import referencial_bp

# Otros módulos
from .models import Categoria, Medida


# Para definir las vistas, se usa el Blueprint para el decorador route
# y no la app como normalmente
# @app.route(...: Se reemplaza @app por @referencial_bp

#########################################################
# VISTAS PARA LAS CATEGORIAS
#########################################################

# Lista de todas las categorias de recetas
@referencial_bp.route('/referencial/lista_categorias')
def Listar_Categorias():
    categorias = Categoria.listar()
    return render_template('/referencial/categoria_list.html', categorias = categorias)

# Consulta una categoria de recetas dada
# El parámetro acción permite "adaptar" el template
@referencial_bp.route('/referencial/consultar_categoria/<id>')
def Consultar_Categoria(id):
    accion = "Consultar"
    categoria = Categoria()
    unaCategoria = categoria.buscar(id)
    return render_template('/referencial/categoria_detail.html', categoria=unaCategoria, accion=accion)

# Crea una categoria de recetas 
# El parámetro acción permite "adaptar" el template
@referencial_bp.route('/referencial/crear_categoria', methods=["GET", "POST"])
def Crear_Categoria():
    accion = "Crear"
    categoria = Categoria()
    if request.method == 'POST':
        categoria.nombre = request.form['nombre']
        categoria.descripcion = request.form['descripcion']

        if categoria.validar():                     
            categoria.guardar()
            mensaje="Categoria " + categoria.nombre + " creada satisfactoriamente" 
            flash(mensaje)
            return redirect(url_for('referencial.Listar_Categorias'))
              
    return render_template('/referencial/categoria_detail.html', categoria=categoria, accion=accion)

# Edita una categoria de recetas dada
# El parámetro acción permite "adaptar" el template
@referencial_bp.route('/referencial/editar_categoria/<int:id>',  methods=["GET", "POST"])
def Editar_Categoria(id):
    accion = "Editar"
    categoria = Categoria()
    unaCategoria = categoria.buscar(id)

    if request.method == 'POST':
        categoria.id = id
        categoria.nombre = request.form['nombre']
        categoria.descripcion = request.form['descripcion']

        if categoria.validar():   
            categoria.guardar()
            mensaje="Categoria " + categoria.nombre + " modificada satisfactoriamente" 
            flash(mensaje)
            return redirect(url_for('referencial.Listar_Categorias'))

    return render_template('/referencial/categoria_detail.html', categoria=unaCategoria, accion=accion)


# Elimina una categoria de recetas dada
@referencial_bp.route('/referencial/eliminar_categoria/<int:id>')
def Eliminar_Categoria(id):
    categoria = Categoria()
    if categoria.borrar(id):
        flash('Categoria eliminada satisfactoriamente')
    
    return redirect(url_for('referencial.Listar_Categorias'))


#########################################################
# VISTAS PARA LAS UNIDADES DE MEDIDA
#########################################################

# Lista de todas las unidades de medida
@referencial_bp.route('/referencial/lista_medidas')
def Listar_Medidas():
    medidas = Medida.listar()
    return render_template('/referencial/medida_list.html', medidas = medidas)

# Consulta una unidad de medida dada
# El parámetro acción permite "adaptar" el template
@referencial_bp.route('/referencial/consultar_medida/<id>')
def Consultar_Medida(id):
    accion = "Consultar"
    medida = Medida()
    unaMedida = medida.buscar(id)
    return render_template('/referencial/medida_detail.html', medida=unaMedida, accion=accion)

# Crea una unidad de medida
# El parámetro acción permite "adaptar" el template
@referencial_bp.route('/referencial/crear_medida', methods=["GET", "POST"])
def Crear_Medida():
    accion = "Crear"
    medida = Medida()
    if request.method == 'POST':
        medida.nombre = request.form['nombre']
        medida.proporcion = request.form['proporcion']

        if medida.validar():                     
            medida.guardar()
            mensaje="Unidad de medida " + medida.nombre + " creada satisfactoriamente" 
            flash(mensaje)
            return redirect(url_for('referencial.Listar_Medidas'))
              
    return render_template('/referencial/medida_detail.html', medida=medida, accion=accion)

# Edita una unidad de medida
# El parámetro acción permite "adaptar" el template
@referencial_bp.route('/referencial/editar_medida/<int:id>',  methods=["GET", "POST"])
def Editar_Medida(id):
    accion = "Editar"
    medida = Medida()
    unaMedida = medida.buscar(id)

    if request.method == 'POST':
        medida.id = id
        medida.nombre = request.form['nombre']
        medida.proporcion = request.form['proporcion']

        if medida.validar():   
            medida.guardar()
            mensaje="Unidad de medida " + medida.nombre + " modificada satisfactoriamente" 
            flash(mensaje)
            return redirect(url_for('referencial.Listar_Medidas'))

    return render_template('/referencial/medida_detail.html', medida=unaMedida, accion=accion)


# Elimina una unidad de medida
@referencial_bp.route('/referencial/eliminar_medida/<int:id>')
def Eliminar_Medida(id):
    medida = Medida()
    if medida.borrar(id):
        flash('Unidad de mdida eliminada satisfactoriamente')
    
    return redirect(url_for('referencial.Listar_Medidas'))





app/referencial/templates/referencial/categoria_detail.html
{% extends "base.html" %}

{% block title %}
  {{ accion }} Categoria {{ super() }}
{% endblock  %}

{% block page_title %}

  <h1 class="text-primary">{{ accion }} Categoria</h1>

{% endblock %}

{% block content %}

    {% if accion == "Consultar" %}
        <form method="GET"> 
        <fieldset disabled>
    {% elif accion == "Crear" %}
        <form action="{{ url_for('referencial.Crear_Categoria') }}" method="POST"> 
        <fieldset enabled>
    {% else %}
        <form action="{{ url_for('referencial.Editar_Categoria', id=categoria.id) }}" method="POST"> 
        <fieldset enabled>
    {% endif %}
          <div class="row border m-3 p-2">
            <div class="col-sm-5">  
                <label for="nombre" class="col-form-label">Nombre</label>
                <div class="col">
                    <input type="text" class="form-control" id="nombre" name="nombre" maxlength=50
                    value={% if accion == "Crear" %} "" {% else %} "{{ categoria.nombre }}" {% endif %} required>
                </div>
            </div>
            <div class="col-sm-7">  
                <label for="descripcion" class="col-form-label">Descripción</label>
                <div class="col">
                    <input type="text" class="form-control" id="descripcion" name="descripcion" maxlength=100
                    value={% if accion == "Crear" %} "" {% else %} "{{ categoria.descripcion }}" {% endif %} >
                </div>
            </div>
          </div>
        </fieldset>

        <footer>
          <div class="d-flex flex-row justify-content-between">
            <div class="p-2">
              <a class="btn btn-primary" href="{{ url_for('referencial.Listar_Categorias') }}" >Volver a la lista</a>
            </div>    
            {% if accion != "Consultar"  %}
              <div class="p-2">
                <button type="Submit" class="btn btn-primary">Validar</button>
              </div>
            {% endif %}        
          </div>
        </footer>

    </form>
       
{% endblock %}

    
      
   

app/referencial/templates/referencial/categoria_list.html
{% extends "base_list.html" %}

{% block title %}
  Lista de Categorias {{ super() }}
{% endblock  %}

{% block page_title %}

  <h1 class="text-primary">Lista de Categorias</h1>

{% endblock %}


    {% block table_head %}
      <tr>
          <th>Nombre<i class="fa fa-sort" aria-hidden="true"></i></th>
          <th>Descripción</th>
          <th>Acciones</th>
      </tr>
    {% endblock table_head %}

    {% block table_body %}

       {% for categoria in categorias %}
          <tr>
             <td>
                <a href="{{ url_for('referencial.Consultar_Categoria', id=categoria.id) }}">
                {{ categoria.nombre }}</a>
             </td>
             <td>
               <p>{{ categoria.descripcion }}</p>
             </td>
             <td>
               <a href="{{ url_for('referencial.Consultar_Categoria', id=categoria.id) }}" class="view" title="View" data-toggle="tooltip"><i class="material-icons">&#xE417;</i></a>
               <a href="{{ url_for('referencial.Editar_Categoria', id=categoria.id) }}" class="edit" title="Edit" data-toggle="tooltip"><i class="material-icons">&#xE254;</i></a>
               <a href="{{ url_for('referencial.Eliminar_Categoria', id=categoria.id) }}" class="delete" title="Delete" data-toggle="tooltip"><i class="material-icons">&#xE872;</i></a>
             </td>
           </tr>
      {% endfor %}   
    {% endblock table_body %}

    <footer>
      {% block others %}
        <div class="col-sm-4">
          <a class="btn btn-primary" href="{{ url_for('referencial.Crear_Categoria') }}" >Nuevo</a>
        </div>
      {% endblock others %}
    </footer>

   


app/referencial/templates/referencial/medida_detail.html
{% extends "base.html" %}

{% block title %}
  {{ accion }} Unidad de Medida {{ super() }}
{% endblock  %}

{% block page_title %}

  <h1 class="text-primary">{{ accion }} Unidad de Medida</h1>

{% endblock %}

{% block content %}

    {% if accion == "Consultar" %}
        <form method="GET"> 
        <fieldset disabled>
    {% elif accion == "Crear" %}
        <form action="{{ url_for('referencial.Crear_Medida') }}" method="POST"> 
        <fieldset enabled>
    {% else %}
        <form action="{{ url_for('referencial.Editar_Medida', id=medida.id) }}" method="POST"> 
        <fieldset enabled>
    {% endif %}
          <div class="row border m-3 p-2">
            <div class="col-sm-5">  
                <label for="nombre" class="col-form-label">Nombre</label>
                <div>
                    <input type="text" class="form-control" id="nombre" name="nombre" maxlength=50
                    value={% if accion == "Crear" %} "" {% else %} "{{ medida.nombre }}" {% endif %} required>
                </div>
            </div>
            <div class="col-sm-7">  
                <label for="descripcion" class="col-form-label">Proporción</label>
                <div>
                    <input type="number" step="0.01" class="form-control text-right" id="proporcion" name="proporcion" 
                    value={% if accion == "Crear" %} "0.00" {% else %} "{{ medida.proporcion }}" {% endif %} required>
                </div>
            </div>
          </div>
        </fieldset>

        <footer>
            <div class="d-flex flex-row justify-content-between">
              <div class="p-2">
                <a class="btn btn-primary" href="{{ url_for('referencial.Listar_Medidas') }}" >Volver a la lista</a>
              </div>    
              {% if accion != "Consultar"  %}
                <div class="p-2">
                  <button type="Submit" class="btn btn-primary">Validar</button>
                </div>
              {% endif %}        
            </div>
        </footer>

    </form>
       
{% endblock %}

    
      
   

app/referencial/templates/referencial/medida_list.html
{% extends "base_list.html" %}

{% block title %}
  Lista de Unidades de Medida {{ super() }}
{% endblock  %}

{% block page_title %}

  <h1 class="text-primary">Lista de Unidades de Medida</h1>

{% endblock %}


    {% block table_head %}
      <tr>
          <th>Nombre<i class="fa fa-sort" aria-hidden="true"></i></th>
          <th>Acciones</th>
      </tr>
    {% endblock table_head %}

    {% block table_body %}

       {% for medida in medidas %}
          <tr>
             <td>
                <a href="{{ url_for('referencial.Consultar_Medida', id=medida.id) }}">
                {{ medida.nombre }}</a>
             </td>
             <td>
               <a href="{{ url_for('referencial.Consultar_Medida', id=medida.id) }}" class="view" title="View" data-toggle="tooltip"><i class="material-icons">&#xE417;</i></a>
               <a href="{{ url_for('referencial.Editar_Medida', id=medida.id) }}" class="edit" title="Edit" data-toggle="tooltip"><i class="material-icons">&#xE254;</i></a>
               <a href="{{ url_for('referencial.Eliminar_Medida', id=medida.id) }}" class="delete" title="Delete" data-toggle="tooltip"><i class="material-icons">&#xE872;</i></a>
             </td>
           </tr>
      {% endfor %}   
    {% endblock table_body %}

    {% block others %}
      <div class="col-sm-4">
        <a class="btn btn-primary" href="{{ url_for('referencial.Crear_Medida') }}" >Nuevo</a>
      </div>
    {% endblock  %}

   
